BoxLayout:
    orientation: 'vertical'

    Button:
        text: 'Clear'
        on_press: app.handle_clear()

    TextInput:
        id: input_name
        text: ''
        hint_text: "Enter your name"
        font_size: 32
        multiline: False
        size_hint_y: 0.2

    Button:
        text: 'Greet'
        on_press: app.handle_greet()

    Label:
        id: output_label
        text: ''
        color: (1, 1, 0, 1)  # Yellow color
        font_size: 36
        size_hint_y: 0.2
